require('settings')
require('packer-config')
-- require('colorschemes-config.nightfox')
require('colorschemes-config.gruvbox')
require('nvimtree-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lsp-config.null-ls')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('twilight-config')
require('blamer-config')
