-- require('packer-config')
require('lazy-config')
require('settings')
-- require('colorschemes-config.nightfox')
-- require('colorschemes-config.nordfox')
-- require('colorschemes-config.tokyonight-moon')
-- require('colorschemes-config.catppuccin')
-- require('colorschemes-config.oceanic')
require('colorschemes-config.gruvbox')
require('nvimtree-config')
require('notify-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lsp-config.null-ls')
require('lualine-config')
require('barbar-config')
require('transparent-config')
require('treesitter-config')
require('telescope-config')
-- require('twilight-config')
require('blamer-config')
require('codeactionmenu-config')
require('rest-config')
require('indentline-config')
require('mappings')
